$(function(){
	$('#wrapper').append('<div class="row border-bottom">'
            +'<nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">'
                    +'<div class="navbar-header">'
                        +'<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="addnew_conpany.html#">'
                        +'</a>'
                    +'</div>'
                    +'<ul class="nav navbar-top-links navbar-right">'
                         +'<li>'
                            +'<span class="m-r-sm text-muted welcome-message">'
                            +'<a href="#" title="返回首页">'
                            +'<div class="glyph fs1">'
                                +'<div class="clearfix bshadow0 pbs">'
                                    +'<span class="icon-ishop_3-01">'
                                    +'</span>'
                                +'</div>'
                            +'</div>'
                            +'</a></span>'
                        +'</li>'
                        +'<li class="dropdown">'
                            +'<a class="dropdown-toggle count-info" data-toggle="dropdown" href="index.html#">'
                                +'<div class="glyph fs1">'
                                    +'<div class="clearfix bshadow0 pbs">'
                                        +'<span class="icon-ishop_3-02">'
                                        +'</span>'
                                        +'<span class="label label-primary">2</span>'
                                    +'</div>'
                                +'</div>'
                            +'</a>'
                            +'<ul class="dropdown-menu dropdown-alerts">'
                                 +'<li>'
                                     +'<a href="mailbox.html">'
                                         +'<div>'
                                            +' <i class="fa fa-envelope fa-fw"></i> 您有16条未读消息'
                                            +' <span class="pull-right text-muted small">4分钟前</span>'
                                         +'</div>'
                                     +'</a>'
                                 +'</li>'
                                 +'<li class="divider"></li>'
                                 +'<li>'
                                     +'<a href="profile.html">'
                                        +' <div>'
                                             +'<i class="fa fa-qq fa-fw"></i> 3条新回复'
                                             +'<span class="pull-right text-muted small">12分钟钱</span>'
                                         +'</div>'
                                     +'</a>'
                                 +'</li>'
                                 +'<li class="divider"></li>'
                                 +'<li>'
                                     +'<div class="text-center link-block">'
                                         +'<a href="notifications.html">'
                                             +'<strong>查看所有 </strong>'
                                             +'<i class="fa fa-angle-right"></i>'
                                         +'</a>'
                                     +'</div>'
                                 +'</li>'
                             +'</ul>'
                         +'</li>'
                         +'<li class="dropdown">'
                             +'<a class="dropdown-toggle count-info" data-toggle="dropdown" href="index.html#">'
                                  +'<div class="glyph fs1">'
                                     +'<div class="clearfix bshadow0 pbs">'
                                         +'<span class="icon-ishop_3-03">'
                                         +'</span>'
                                     +'</div>'
                                 +'</div>'
                             +'</a>'
                             +'<ul class="dropdown-menu dropdown-messages">'
                                 +'<li>'
                                     +'<div class="dropdown-messages-box">'
                                         +'<a href="profile.html" class="pull-left">'
                                            +' <img alt="image" class="img-circle" src="../img/a7.jpg">'
                                         +'</a>'
                                         +'<div class="media-body">'
                                             +'<small class="pull-right">46小时前</small>'
                                             +'<strong>小四</strong> 项目已处理完结'
                                             +'<br>'
                                             +'<small class="text-muted">3天前 2014.11.8</small>'
                                        +' </div>'
                                    +' </div>'
                                 +'</li>'
                                 +'<li class="divider"></li>'
                                +' <li>'
                                     +'<div class="dropdown-messages-box">'
                                        +' <a href="profile.html" class="pull-left">'
                                             +'<img alt="image" class="img-circle" src="../img/a4.jpg">'
                                         +'</a>'
                                         +'<div class="media-body ">'
                                             +'<small class="pull-right text-navy">25小时前</small>'
                                             +'<strong>国民岳父</strong> 这是一条测试信息'
                                            +' <br>'
                                            +' <small class="text-muted">昨天</small>'
                                        +' </div>'
                                     +'</div>'
                                 +'</li>'
                                 +'<li class="divider"></li>'
                                 +'<li>'
                                    +' <div class="text-center link-block">'
                                         +'<a href="mailbox.html">'
                                             +'<i class="fa fa-envelope"></i>  <strong> 查看所有消息</strong>'
                                         +'</a>'
                                     +'</div>'
                                 +'</li>'
                             +'</ul>'
                         +'</li>'
                         +'<li>'
                             +'<a href="login.html">'
                                 +'<div class="glyph fs1">'
                                     +'<div class="clearfix bshadow0 pbs">'
                                         +'<span class="icon-ishop_3-04">'
                                        +' </span>'
                                     +'</div>'
                                 +'</div>'
                             +'</a>'
                         +'</li>'
                         +'<li class="search_box">'
                             +'<form role="search" class="navbar-form-custom" method="post" action="search_results.html">'
                                +' <div class="form-group">'
                                    +' <input type="text" placeholder="" class="form-control" name="top-search" id="top-search">'
                                     +'<i class="icon-ishop_3-05" id="search_icon"></i>'
                                 +'</div>'
                             +'</form>'
                         +'</li>'
                         +'<li class="personal_menu"><span class="user_img"><img src="../img/profile_small.jpg" alt="" /></span>'
                         	+'<span class="dropdown-menu animated fadeInRight m-t-xs" style="margin-top:20px">'
						        +'<ul >'
						            +'<li><a href="#"><i class="icon-ishop_3-06"></i>我的账号</a>'
						            +'</li>'
						            +'<li><a href="#"><i class="icon-ishop_3-07"></i>退出登录</a>'
						            +'</li>'
						            +'<li><a href="#"><i class="icon-ishop_3-08"></i>帮助手册</a>'
						            +'</li>'
						        +'</ul>'
						            +'<s>'
						            +'</s>'
						    +'</span>'
                         +'</li>'
                    +'</ul>'
            +' </nav>'
        +'</div>'
        +'<nav class="navbar-default navbar-static-side" role="navigation">'
            +'<div class="sidebar-collapse">'
                +'<ul class="nav" id="side-menu">'
                    +'<li>'
                         +'<a href="#">'
                            +'<i class="icon-ishop_2-07"></i>'
                            +' <span class="nav-label">企业管理</span>'
                         +'</a>'
                    +'</li>'
                    +'<li>'
                        +'<a href="#"><i class="icon-ishop_2-01"></i> <span class="nav-label">店铺管理</span>'
                        +'</a>'
                    +'</li>'
                    +'<li>'
                        +'<a href="#"><i class="icon-ishop_2-02"></i> <span class="nav-label">员工管理</span><span class="fa arrow"></span></a>'
                        +'<ul class="nav nav-second-level">'
                            +'<li ><a href="#"><label></label>员工列表</a>'
                            +'</li>'
                            +'<li><a href="#"><label></label>签到管理</a>'
                            +'</li>'
                        +'</ul>'
                    +'</li>'
                    +'<li>'
                        +'<a href="#"><i class="icon-ishop_2-08"></i> <span class="nav-label">业绩管理</span><span class="fa arrow"></span></a>'
                        +'<ul class="nav nav-second-level">'
                            +'<li><a href="#"><label></label>店铺业绩目标</a>'
                            +'</li>'
                            +'<li><a href="#"><label></label>员工业绩目标</a>'
                            +'</li>'
                        +' </ul>'
                    +'</li>'
                    +'<li>'
                         +'<a href="#"><i class="icon-ishop_2-03"></i> <span class="nav-label">会员管理</span><span class="fa arrow"></span>'
                         +'</a>'
                         +'<ul class="nav nav-second-level">'
                            +' <li><a href="#"><label></label>会员列表</a>'
                             +'</li>'
                             +'<li><a href="#"><label></label>会员标签管理</a>'
                             +'</li>'
                             +'<li><a href="#"><label></label>回访记录管理</a>'
                             +'</li>'
                         +'</ul>'
                    +'</li>'
                    +'<li>'
                         +'<a href="#"><i class="icon-ishop_2-04"></i> <span class="nav-label">商品管理</span><span class="fa arrow"></span></a>'
                         +'<ul class="nav nav-second-level">'
                             +'<li><a href="#"><label></label>商品培训(FAB)</a>'
                             +'</li>'
                             +'<li><a href="#"><label></label>秀搭管理</a>'
                             +'</li>'
                         +'</ul>'
                    +'</li>'
                    +'<li>'
                         +'<a href="#"><i class="icon-ishop_2-05"></i> <span class="nav-label">消息管理</span><span class="fa arrow"></span></a>'
                         +'<ul class="nav nav-second-level">'
                             +'<li><a href="#"><label></label>爱秀消息</a>'
                             +'</li>'
                             +'<li><a href="#"><label></label>手机短信</a>'
                             +'</li>'
                         +'</ul>'
                    +'</li>'
                    +'<li>'
                         +'<a href="#"><i class="icon-ishop_2-10"></i> <span class="nav-label">用户及权限</span><span class="fa arrow"></span></a>'
                         +'<ul class="nav nav-second-level">'
                             +'<li><a href="#"><label></label>角色定义</a>'
                             +'</li>'
                             +'<li><a href="#"><label></label>群组管理</a>'
                             +'</li>'
                             +'<li><a href="#"><label></label>用户管理</a>'
                             +'</li>'
                         +'</ul>'
                    +'</li>'
                    +'<li>'
                         +'<a href="#"><i class="icon-ishop_2-09"></i> <span class="nav-label">系统管理</span><span class="fa arrow"></span></a>'
                         +'<ul class="nav nav-second-level">'
                             +'<li><a href="#"><label></label>用户反馈</a>'
                             +'</li>'
                             +'<li><a href="#"><label></label>APP版本控制</a>'
                             +'</li>'
                             +'<li><a href="#"><label></label>缓存管理</a>'
                             +'</li>'
                             +'<li><a href="#"><label></label>接口管理</a>'
                             +'</li>'
                             +'<li><a>日志管理<span class="fa arrow" style="display:none"></span></a>'
                                 +'<ul class="nav nav-third-level">'
                                     +'<li><a href="#"><label></label>错误日志</a>'
                                     +'</li>'
                                     +'<li><a href="#"><label></label>登录日志</a>'
                                     +'</li>'
                                     +'<li><a href="#"><label></label>验证码管理</a>'
                                     +'</li>'
                                 +'</ul>'
                             +'</li>'
                         +'</ul>'
                    +'</li>'
                +'</ul>'
            +'</div>'
        +'</nav>'
    );
    $(document).bind('click',function(e){
        var target = $(e.target);
        if(target.closest(".personal_menu").length == 0){
            $('.personal_menu').removeClass('open');
        }else{
            $('.personal_menu').toggleClass('open');
        }
    });
});
